# Generated by Django 5.0.6 on 2024-06-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_maintenance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="description",
            field=models.TextField(default="Maintenance mode"),
        ),
    ]
