import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';

import { Toaster } from '@/components/ui/toaster';
import { NotificationProvider } from '@/providers/NotificationProvider';
import TableEvents from '@/components/TableEvents/TableEvents';
import Notification from '@/components/Notification/Notification';

const fontSans = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        {children}
        <NotificationProvider>
          <div>data</div>
          <Notification />
        </NotificationProvider>
        <Toaster />
      </body>
    </html>
  );
}
